eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  healthcheck:
    enabled: true
server:
  port: 8762
spring:
  application:
    name: auth-service
  thymeleaf:
    cache: false
  redis:
    database: 0
    host: localhost
    port: 6379
    password: passw0rd
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0
swagger:
  package: com.mcs.cysoft.auth.rest.controller