eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  healthcheck:
    enabled: true
server:
  port: 8762
spring:
  application:
    name: auth-service
  thymeleaf:
    cache: false